version: '3.4'

services:
  nettools:
    image: nettools
    build:
      context: net-tools
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
